# Wrangler configuration
name = "easycal"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".next/standalone"

# Environment variables
[vars]
APP_BASE_URL = "https://easycal.enrollio.ai"
HL_CLIENT_ID = "68b96169e165955a7edc20b3-mf58ywbo"
OAUTH_REDIRECT_URL = "https://services.leadconnectorhq.com/oauth/clients/68b96169e165955a7edc20b3/authentication/oauth2/callback"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "easycal-db"
database_id = "066771b0-ce11-4890-b95d-8427058dd129"

# KV namespace configuration
[[kv_namespaces]]
binding = "EASYCAL_SESSIONS"
id = "0cb05fe2ee44425f9952d1a73d5d1651"

# Queue configuration
[[queues.producers]]
queue = "easycal-jobs"
binding = "EASYCAL_JOBS"

